[package]
name = "substrate-gateway"
version = "2.7.0"
description = "Graphql server for substrate-ingest"
edition = "2021"

[profile.release]
lto = true
codegen-units = 1
opt-level = 'z'

[dependencies]
async-graphql = { version = "4.0.3", features = ["chrono"] }
async-graphql-actix-web = "4.0.3"
async-trait = "0.1.52"
actix-web = { version = "4.1.0", default-features = false, features = ["macros"] }
sqlx = { version = "=0.7.3", features = [
  "runtime-tokio-rustls",
  "postgres",
  "macros",
  "chrono",
  "json",
  "rust_decimal",
] }
rust_decimal = "1.25.0"
chrono = "=0.4.22"
serde = "1.0"
serde_json = "1.0"
prometheus = { version = "0.13", default-features = false }
lazy_static = "1.4.0"
mime = "0.3.16"
tracing = "0.1.35"
tracing-subscriber = { version = "0.3.11", features = ["json", "env-filter"] }
futures-util = "0.3.21"
uuid = { version = "1.1.2", features = ["v4"] }
libc = "0.2"
clap = { version = "3.1.18", features = ["derive"] }

substrate-archive = { path = "./substrate-archive", version = "0.1.0", features = ["clap"] }

[dev-dependencies]
reqwest = { version = "0.11.11", features = ["json"] }
serde = { version = "1", features = ["derive"], default-features = false }

[workspace]
members = [".", "substrate-archive"]
